
export const VIEW_PANEL_SIZE = {
  PROMOBAR_HEIGHT: 20,
  TOPBAR_HEIGHT: 70,
  SIDEMENU_WIDTH: 80,
  LEFTBAR_WIDTH: 250,
  RIGHTBAR_WIDTH: 250,
  FOOTER_BOTTOM: 0,
  FOOTER_HEIGHT: 50,
};


export const EDITOR_SETTINS = {
  DEBOUNCE: 10,
};
